import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import { logger } from '../config/logger.js';

// Audit Trail exports are a flat log table (Time/User/Role/Branch/Module/
// Action/Description/Status), not a summary+breakdown aggregate report —
// deliberately NOT routed through reportConfig.js/reportPdf.service.js's
// config-driven machinery, which is shaped around the 12 aggregate report
// types (KPI cards, grouped breakdowns) and would need to be force-fit for
// a raw row export. This mirrors that machinery's brand palette, header/
// footer conventions, and CSV/Excel styling by hand instead, so exports
// read as the same brand without touching the reporting engine at all.

const COLOR_NAVY = '#0B1F4D';
const COLOR_MUTED = '#64748B';
const COLOR_BORDER = '#E2E8F0';
const COLOR_ROW_ALT = '#F8FAFC';
const COLOR_WHITE = '#FFFFFFFF';

const MM_TO_PT = 2.83465;
const mm = (value) => value * MM_TO_PT;
const PAGE_MARGIN = mm(12);
const CONTENT_WIDTH = mm(297) - PAGE_MARGIN * 2; // landscape A4 — 8 columns needs the width

const COLUMNS = [
  { key: 'created_at', label: 'Time', width: 0.13, format: (v) => new Date(v).toLocaleString('en-TZ', { dateStyle: 'medium', timeStyle: 'short' }) },
  { key: 'user_name', label: 'User', width: 0.13, format: (v) => v || 'System' },
  { key: 'role_name', label: 'Role', width: 0.1, format: (v) => v || '-' },
  { key: 'branch_name', label: 'Branch', width: 0.1, format: (v) => v || 'All Branches' },
  { key: 'module', label: 'Module', width: 0.1, format: (v) => v },
  { key: 'action', label: 'Action', width: 0.13, format: (v) => v },
  { key: 'description', label: 'Description', width: 0.23, format: (v) => v || '' },
  { key: 'status', label: 'Status', width: 0.08, format: (v) => (v === 'failed' ? 'Failed' : 'Success') },
];

function dateRangeLabel(dateFrom, dateTo) {
  return dateFrom && dateTo ? `${dateFrom} to ${dateTo}` : 'All time';
}

export function buildAuditLogFilename(ext) {
  const stamp = new Date().toISOString().slice(0, 10);
  return `audit-trail-${stamp}.${ext}`;
}

export function buildAuditLogPdf(rows, { dateFrom, dateTo, generatedByName } = {}) {
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: PAGE_MARGIN, bufferPages: true });
  const chunks = [];
  doc.on('data', (chunk) => chunks.push(chunk));

  function drawHeader() {
    doc.fontSize(8).font('Helvetica-Bold').fillColor(COLOR_MUTED).text('JOZZY SALES MANAGEMENT SYSTEM', PAGE_MARGIN, PAGE_MARGIN);
    doc.fontSize(16).font('Helvetica-Bold').fillColor(COLOR_NAVY).text('Audit Trail Report', PAGE_MARGIN, doc.y + 2);
    doc.fontSize(9).font('Helvetica').fillColor(COLOR_MUTED).text(dateRangeLabel(dateFrom, dateTo), PAGE_MARGIN, doc.y);
    if (generatedByName) doc.text(`Generated by: ${generatedByName} on ${new Date().toLocaleString('en-TZ', { dateStyle: 'medium', timeStyle: 'short' })}`, PAGE_MARGIN, doc.y);
    doc.moveDown(0.4);
    doc.moveTo(PAGE_MARGIN, doc.y).lineTo(PAGE_MARGIN + CONTENT_WIDTH, doc.y).strokeColor(COLOR_BORDER).stroke();
    doc.moveDown(0.4);
  }

  function drawTableHeader() {
    const rowY = doc.y;
    const rowHeight = mm(6);
    doc.roundedRect(PAGE_MARGIN, rowY - 2, CONTENT_WIDTH, rowHeight, 2).fill(COLOR_NAVY);
    doc.fontSize(8).font('Helvetica-Bold').fillColor(COLOR_WHITE);
    let x = PAGE_MARGIN;
    COLUMNS.forEach((col) => {
      const w = CONTENT_WIDTH * col.width;
      doc.text(col.label, x + 3, rowY, { width: w - 6 });
      x += w;
    });
    doc.y = rowY + rowHeight;
    doc.fillColor(COLOR_NAVY).font('Helvetica');
  }

  drawHeader();
  drawTableHeader();
  doc.on('pageAdded', () => {
    doc.y = PAGE_MARGIN;
    drawTableHeader();
  });

  const rowHeight = mm(6);
  rows.forEach((row, index) => {
    if (doc.y + rowHeight > doc.page.height - PAGE_MARGIN - mm(8)) {
      doc.addPage();
    }
    const rowY = doc.y;
    if (index % 2 === 1) doc.rect(PAGE_MARGIN, rowY - 1, CONTENT_WIDTH, rowHeight).fill(COLOR_ROW_ALT);
    doc.fillColor(COLOR_NAVY);
    let x = PAGE_MARGIN;
    COLUMNS.forEach((col) => {
      const w = CONTENT_WIDTH * col.width;
      doc.fontSize(7.5).text(String(col.format(row[col.key])), x + 3, rowY, { width: w - 6, height: rowHeight, ellipsis: true });
      x += w;
    });
    doc.y = rowY + rowHeight;
  });

  const range = doc.bufferedPageRange();
  const bottom = doc.page.height - PAGE_MARGIN - mm(6);
  for (let i = 0; i < range.count; i += 1) {
    doc.switchToPage(range.start + i);
    doc.fontSize(8).font('Helvetica').fillColor(COLOR_MUTED)
      .text(`Page ${i + 1} of ${range.count}`, PAGE_MARGIN, bottom, { width: CONTENT_WIDTH, align: 'center', lineBreak: false });
  }

  doc.end();

  return new Promise((resolve, reject) => {
    doc.on('end', () => {
      logger.info('Audit trail PDF generated', { rows: rows.length });
      resolve(Buffer.concat(chunks));
    });
    doc.on('error', reject);
  });
}

export async function buildAuditLogExcel(rows, { dateFrom, dateTo, generatedByName } = {}) {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Audit Trail');

  sheet.mergeCells('A1:H1');
  sheet.getCell('A1').value = 'Audit Trail Report';
  sheet.getCell('A1').font = { bold: true, size: 16, color: { argb: 'FF0B1F4D' } };

  sheet.getCell('A2').value = dateRangeLabel(dateFrom, dateTo);
  sheet.getCell('A2').font = { italic: true, color: { argb: 'FF64748B' } };
  if (generatedByName) {
    sheet.getCell('A3').value = `Generated by: ${generatedByName} on ${new Date().toLocaleString('en-TZ', { dateStyle: 'medium', timeStyle: 'short' })}`;
    sheet.getCell('A3').font = { size: 9, color: { argb: 'FF64748B' } };
  }

  const headerRowIndex = 5;
  const headerRow = sheet.getRow(headerRowIndex);
  headerRow.values = COLUMNS.map((c) => c.label);
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0B1F4D' } };
  });

  COLUMNS.forEach((col, index) => {
    sheet.getColumn(index + 1).width = col.key === 'description' ? 40 : 20;
  });

  rows.forEach((row, index) => {
    const excelRow = sheet.addRow(COLUMNS.map((c) => c.format(row[c.key])));
    if (index % 2 === 1) {
      excelRow.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      });
    }
  });

  sheet.views = [{ state: 'frozen', ySplit: headerRowIndex }];

  return workbook;
}

// Ported from reportCsv.service.js's own port of src/utils/exportCsv.js —
// same escaping rules and UTF-8 BOM so Excel opens it cleanly.
const BOM = String.fromCharCode(0xfeff);

function csvEscape(value) {
  const str = String(value ?? '');
  if (/[",\n]/.test(str)) return `"${str.replace(/"/g, '""')}"`;
  return str;
}

export function buildAuditLogCsv(rows, { dateFrom, dateTo, generatedByName } = {}) {
  const lines = [
    csvEscape('Audit Trail Report'),
    csvEscape(dateRangeLabel(dateFrom, dateTo)),
    ...(generatedByName ? [`Prepared By,${csvEscape(generatedByName)}`] : []),
    '',
    COLUMNS.map((c) => csvEscape(c.label)).join(','),
    ...rows.map((row) => COLUMNS.map((c) => csvEscape(c.format(row[c.key]))).join(',')),
  ];
  return BOM + lines.join('\n');
}
