import ExcelJS from 'exceljs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../config/logger.js';
import { resolveConfig, humanize, MONEY_KEYS } from './reportConfig.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const UPLOADS_ROOT = path.join(__dirname, '..', 'uploads');

const COLOR_PRIMARY = 'FF0F172A';
const COLOR_ACCENT = 'FF22C55E';
const COLOR_ROW_ALT = 'FFF8FAFC';
const COLOR_WHITE = 'FFFFFFFF';

// Same local-path-only restriction as reportPdf.service.js — a Cloudinary
// (remote URL) logo is skipped rather than fetched over HTTP for embedding.
function resolveLocalLogoPath(logoPath) {
  if (!logoPath || !logoPath.startsWith('/uploads/')) return null;
  const absPath = path.join(UPLOADS_ROOT, logoPath.replace('/uploads/', ''));
  return fs.existsSync(absPath) ? absPath : null;
}

function isDateLabelColumn(key) {
  return key === 'label' && key !== null;
}

export async function buildReportExcel(type, report, { dateFrom, dateTo, company, generatedByName, filtersLabel } = {}) {
  const config = resolveConfig(type, report);
  const dateRangeLabel = dateFrom && dateTo ? `${dateFrom} to ${dateTo}` : 'All time';

  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'JOZZY Sales Management System';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(config.title.slice(0, 31));

  let currentRow = 1;
  const logoPath = resolveLocalLogoPath(company?.logo_path);
  if (logoPath) {
    try {
      const ext = path.extname(logoPath).replace('.', '').toLowerCase();
      const imageId = workbook.addImage({ filename: logoPath, extension: ext === 'jpg' ? 'jpeg' : ext });
      sheet.addImage(imageId, { tl: { col: 0, row: 0 }, ext: { width: 90, height: 60 } });
      currentRow = 4;
    } catch (err) {
      logger.warn('Report Excel: failed to embed company logo, skipping', { error: err.message });
    }
  }

  sheet.getCell(`A${currentRow}`).value = 'JOZZY SALES MANAGEMENT SYSTEM';
  sheet.getCell(`A${currentRow}`).font = { bold: true, size: 9, color: { argb: 'FF64748B' } };
  currentRow += 1;

  sheet.mergeCells(`A${currentRow}:F${currentRow}`);
  const titleCell = sheet.getCell(`A${currentRow}`);
  titleCell.value = `${config.title} Report`;
  titleCell.font = { bold: true, size: 16, color: { argb: COLOR_PRIMARY } };
  currentRow += 1;

  sheet.getCell(`A${currentRow}`).value = dateRangeLabel;
  sheet.getCell(`A${currentRow}`).font = { italic: true, color: { argb: 'FF64748B' } };
  currentRow += 1;

  if (generatedByName) {
    sheet.getCell(`A${currentRow}`).value = `Generated by: ${generatedByName} on ${new Date().toLocaleString('en-TZ', { dateStyle: 'medium', timeStyle: 'short' })}`;
    sheet.getCell(`A${currentRow}`).font = { size: 9, color: { argb: 'FF64748B' } };
    currentRow += 1;
  }
  if (filtersLabel) {
    sheet.getCell(`A${currentRow}`).value = `Filters: ${filtersLabel}`;
    sheet.getCell(`A${currentRow}`).font = { size: 9, color: { argb: 'FF64748B' } };
    currentRow += 1;
  }
  currentRow += 1;

  if (report.summary && config.summaryLabels) {
    sheet.getCell(`A${currentRow}`).value = 'Summary';
    sheet.getCell(`A${currentRow}`).font = { bold: true, size: 12, color: { argb: COLOR_PRIMARY } };
    currentRow += 1;
    Object.entries(config.summaryLabels).forEach(([key, label]) => {
      const value = report.summary[key];
      sheet.getCell(`A${currentRow}`).value = label;
      sheet.getCell(`A${currentRow}`).font = { bold: true };
      const valueCell = sheet.getCell(`B${currentRow}`);
      valueCell.value = value;
      if (MONEY_KEYS.has(key)) valueCell.numFmt = '"TZS" #,##0.00';
      currentRow += 1;
    });
    currentRow += 1;
  }

  if (Array.isArray(report.analysis) && report.analysis.length > 0) {
    sheet.getCell(`A${currentRow}`).value = 'Business Summary';
    sheet.getCell(`A${currentRow}`).font = { bold: true, size: 12, color: { argb: COLOR_PRIMARY } };
    currentRow += 1;
    report.analysis.forEach((line) => {
      sheet.getCell(`A${currentRow}`).value = `•  ${line}`;
      currentRow += 1;
    });
    currentRow += 1;
  }

  config.breakdowns.forEach(({ key, title: breakdownTitle, labelHeader }) => {
    const rows = report[key];

    sheet.getCell(`A${currentRow}`).value = breakdownTitle;
    sheet.getCell(`A${currentRow}`).font = { bold: true, size: 12, color: { argb: COLOR_PRIMARY } };
    currentRow += 1;

    if (!rows || rows.length === 0) {
      sheet.getCell(`A${currentRow}`).value = 'No data for the selected filters.';
      sheet.getCell(`A${currentRow}`).font = { italic: true, color: { argb: 'FF64748B' } };
      currentRow += 2;
      return;
    }

    const columns = Object.keys(rows[0]).filter((c) => c !== 'id' && c !== 'code');
    const headerRowIndex = currentRow;

    columns.forEach((c, colIndex) => {
      const cell = sheet.getCell(headerRowIndex, colIndex + 1);
      cell.value = c === 'label' ? labelHeader : humanize(c);
      cell.font = { bold: true, color: { argb: COLOR_WHITE } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLOR_PRIMARY } };
    });
    currentRow += 1;

    const totalColumn = columns.find((c) => typeof rows[0][c] === 'number' && MONEY_KEYS.has(c));
    let runningTotal = 0;

    rows.forEach((row, rowIndex) => {
      columns.forEach((c, colIndex) => {
        const cell = sheet.getCell(currentRow, colIndex + 1);
        cell.value = row[c];
        if (MONEY_KEYS.has(c) && typeof row[c] === 'number') cell.numFmt = '"TZS" #,##0.00';
        if (isDateLabelColumn(c) && /^\d{4}-\d{2}-\d{2}/.test(String(row[c]))) cell.numFmt = 'yyyy-mm-dd';
        if (rowIndex % 2 === 1) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLOR_ROW_ALT } };
      });
      if (totalColumn) runningTotal += Number(row[totalColumn]) || 0;
      currentRow += 1;
    });

    if (totalColumn) {
      const totalColIndex = columns.indexOf(totalColumn);
      const labelCell = sheet.getCell(currentRow, 1);
      labelCell.value = 'Grand Total';
      labelCell.font = { bold: true, color: { argb: COLOR_WHITE } };
      labelCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLOR_ACCENT } };
      const totalCell = sheet.getCell(currentRow, totalColIndex + 1);
      totalCell.value = runningTotal;
      totalCell.numFmt = '"TZS" #,##0.00';
      totalCell.font = { bold: true, color: { argb: COLOR_WHITE } };
      totalCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLOR_ACCENT } };
      for (let col = 1; col <= columns.length; col += 1) {
        if (col === totalColIndex + 1 || col === 1) continue;
        const cell = sheet.getCell(currentRow, col);
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLOR_ACCENT } };
      }
      currentRow += 1;
    }

    // Freeze the header row of the first (and usually largest) breakdown
    // table so it stays visible while scrolling.
    if (!sheet.views?.length) {
      sheet.views = [{ state: 'frozen', ySplit: headerRowIndex }];
    }

    currentRow += 1;
  });

  // Auto column width — measured off every cell actually written, capped so
  // one long outlier value can't blow the sheet out.
  sheet.columns.forEach((column) => {
    let maxLength = 10;
    column.eachCell?.({ includeEmpty: false }, (cell) => {
      const length = String(cell.value ?? '').length;
      if (length > maxLength) maxLength = length;
    });
    column.width = Math.min(maxLength + 2, 40);
  });

  return workbook;
}
