import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';
import { logger } from '../config/logger.js';
import { resolveConfig, formatCell, humanize, MONEY_KEYS } from './reportConfig.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const UPLOADS_ROOT = path.join(__dirname, '..', 'uploads');

const MM_TO_PT = 2.83465;
const mm = (value) => value * MM_TO_PT;

const PAGE_MARGIN = mm(15);
const CONTENT_WIDTH = mm(210) - PAGE_MARGIN * 2;

// Brand palette — exact hex values from src/styles/colors.css, so the PDF
// matches the app's actual palette instead of a set of generic grays.
const COLOR_PRIMARY = '#0F172A';
const COLOR_ACCENT = '#22C55E';
const COLOR_MUTED = '#64748B';
const COLOR_BORDER = '#E2E8F0';
const COLOR_ROW_ALT = '#F8FAFC';
const COLOR_WHITE = '#FFFFFF';

function divider(doc, color = COLOR_BORDER) {
  doc.moveDown(0.3);
  doc.moveTo(PAGE_MARGIN, doc.y).lineTo(PAGE_MARGIN + CONTENT_WIDTH, doc.y).strokeColor(color).stroke();
  doc.moveDown(0.3);
}

// Only handles a locally-stored logo (logo_path starting with "/uploads/");
// a Cloudinary-hosted logo is a remote URL and would need an async fetch to
// embed, which isn't worth the extra request/failure surface for a PDF
// header image — those deployments simply get the text-only header, same
// as if no logo were configured at all.
function resolveLocalLogoPath(logoPath) {
  if (!logoPath || !logoPath.startsWith('/uploads/')) return null;
  const absPath = path.join(UPLOADS_ROOT, logoPath.replace('/uploads/', ''));
  return fs.existsSync(absPath) ? absPath : null;
}

function drawHeader(doc, { config, dateRangeLabel, company, generatedByName, filtersLabel }) {
  const logoPath = resolveLocalLogoPath(company?.logo_path);
  const textLeft = PAGE_MARGIN + (logoPath ? mm(22) : 0);

  if (logoPath) {
    try {
      doc.image(logoPath, PAGE_MARGIN, doc.y, { width: mm(18) });
    } catch (err) {
      logger.warn('Report PDF: failed to embed company logo, falling back to text-only header', { error: err.message });
    }
  }

  const headerTop = doc.y;
  doc.fontSize(8).font('Helvetica-Bold').fillColor(COLOR_MUTED)
    .text('JOZZY SALES MANAGEMENT SYSTEM', textLeft, headerTop, { width: CONTENT_WIDTH - (textLeft - PAGE_MARGIN) });
  doc.fontSize(16).font('Helvetica-Bold').fillColor(COLOR_PRIMARY)
    .text(`${config.title} Report`, textLeft, doc.y, { width: CONTENT_WIDTH - (textLeft - PAGE_MARGIN) });
  doc.fontSize(9).font('Helvetica').fillColor(COLOR_MUTED)
    .text(dateRangeLabel, textLeft, doc.y, { width: CONTENT_WIDTH - (textLeft - PAGE_MARGIN) });

  doc.y = Math.max(doc.y, headerTop + mm(18));
  doc.x = PAGE_MARGIN;

  doc.fontSize(8).font('Helvetica').fillColor(COLOR_MUTED);
  if (generatedByName) {
    doc.text(`Generated by: ${generatedByName} on ${new Date().toLocaleString('en-TZ', { dateStyle: 'medium', timeStyle: 'short' })}`, { width: CONTENT_WIDTH });
  }
  if (filtersLabel) {
    doc.text(`Filters: ${filtersLabel}`, { width: CONTENT_WIDTH });
  }
  doc.fillColor(COLOR_PRIMARY);

  divider(doc, COLOR_ACCENT);
}

function drawFooters(doc) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i += 1) {
    doc.switchToPage(range.start + i);
    const bottom = doc.page.height - PAGE_MARGIN + mm(4);
    doc.fontSize(8).font('Helvetica').fillColor(COLOR_MUTED)
      .text(`Page ${i + 1} of ${range.count}`, PAGE_MARGIN, bottom, { width: CONTENT_WIDTH, align: 'center' });
  }
}

export function buildReportPdf(type, report, { dateFrom, dateTo, company, generatedByName, filtersLabel } = {}) {
  const config = resolveConfig(type, report);
  const dateRangeLabel = dateFrom && dateTo ? `${dateFrom} to ${dateTo}` : 'All time';

  const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true });
  const chunks = [];
  doc.on('data', (chunk) => chunks.push(chunk));

  drawHeader(doc, { config, dateRangeLabel, company, generatedByName, filtersLabel });

  if (report.summary && config.summaryLabels) {
    doc.fontSize(11).font('Helvetica-Bold').fillColor(COLOR_PRIMARY).text('Summary', { width: CONTENT_WIDTH });
    doc.moveDown(0.2);
    doc.fontSize(9).font('Helvetica').fillColor(COLOR_PRIMARY);
    Object.entries(config.summaryLabels).forEach(([key, label]) => {
      doc.text(`${label}: ${formatCell(key, report.summary[key])}`, { width: CONTENT_WIDTH });
    });
    divider(doc);
  }

  config.breakdowns.forEach(({ key, title: breakdownTitle, labelHeader }) => {
    const rows = report[key];

    doc.fontSize(11).font('Helvetica-Bold').fillColor(COLOR_PRIMARY).text(breakdownTitle, { width: CONTENT_WIDTH });
    doc.moveDown(0.2);

    if (!rows || rows.length === 0) {
      doc.fontSize(9).font('Helvetica').fillColor(COLOR_MUTED).text('No data for the selected filters.', { width: CONTENT_WIDTH });
      doc.fillColor(COLOR_PRIMARY);
      divider(doc);
      return;
    }

    const columns = Object.keys(rows[0]).filter((c) => c !== 'id' && c !== 'code');
    const columnWidth = CONTENT_WIDTH / columns.length;
    const rowHeight = mm(6);

    doc.fontSize(8).font('Helvetica-Bold').fillColor(COLOR_WHITE);
    let rowY = doc.y;
    doc.rect(PAGE_MARGIN, rowY - 2, CONTENT_WIDTH, rowHeight).fill(COLOR_PRIMARY);
    doc.fillColor(COLOR_WHITE);
    columns.forEach((c, index) => {
      doc.text(c === 'label' ? labelHeader : humanize(c), PAGE_MARGIN + index * columnWidth + 2, rowY, { width: columnWidth - 4 });
    });
    doc.y = rowY + rowHeight;
    doc.font('Helvetica');

    // A money-bearing column (if any) gets summed into a Grand Total row
    // appended after the data — the first numeric column flagged as money
    // in reportConfig's MONEY_KEYS, matching what the UI's own summary
    // cards already treat as the report's headline currency figure.
    const totalColumn = columns.find((c) => typeof rows[0][c] === 'number' && MONEY_KEYS.has(c));
    let runningTotal = 0;

    rows.forEach((row, index) => {
      rowY = doc.y;
      if (index % 2 === 1) {
        doc.rect(PAGE_MARGIN, rowY - 1, CONTENT_WIDTH, rowHeight).fill(COLOR_ROW_ALT);
      }
      doc.fillColor(COLOR_PRIMARY);
      columns.forEach((c, colIndex) => {
        doc.fontSize(8).text(formatCell(c, row[c]), PAGE_MARGIN + colIndex * columnWidth + 2, rowY, { width: columnWidth - 4 });
      });
      if (totalColumn) runningTotal += Number(row[totalColumn]) || 0;
      doc.y = rowY + rowHeight;
    });

    if (totalColumn) {
      rowY = doc.y;
      doc.rect(PAGE_MARGIN, rowY - 1, CONTENT_WIDTH, rowHeight).fill(COLOR_ACCENT);
      doc.fillColor(COLOR_WHITE).font('Helvetica-Bold');
      const totalColIndex = columns.indexOf(totalColumn);
      doc.text('Grand Total', PAGE_MARGIN + 2, rowY, { width: columnWidth * totalColIndex - 4 });
      doc.text(formatCell(totalColumn, runningTotal), PAGE_MARGIN + totalColIndex * columnWidth + 2, rowY, { width: columnWidth - 4 });
      doc.y = rowY + rowHeight;
      doc.font('Helvetica').fillColor(COLOR_PRIMARY);
    }

    divider(doc);
  });

  drawFooters(doc);
  doc.end();

  return new Promise((resolve, reject) => {
    doc.on('end', () => {
      logger.info('Report PDF generated', { type });
      resolve(Buffer.concat(chunks));
    });
    doc.on('error', reject);
  });
}
